// Mocks generated by Mockito 5.4.6 from annotations
// in ui/test/features/workflow/view_models/workspace_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i2;
import 'dart:ui' as _i11;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:ui/core/api_client.dart' as _i13;
import 'package:ui/features/assets/models/asset.dart' as _i4;
import 'package:ui/features/assets/services/asset_storage_service.dart' as _i16;
import 'package:ui/features/tasks/task_command.dart' as _i15;
import 'package:ui/features/workflow/models/asset_node.dart' as _i9;
import 'package:ui/features/workflow/models/execution_result.dart' as _i3;
import 'package:ui/features/workflow/models/workflow_models.dart' as _i10;
import 'package:ui/features/workflow/models/workspace_models.dart' as _i7;
import 'package:ui/features/workflow/services/session_persistence_service.dart'
    as _i5;
import 'package:ui/features/workflow/services/workflow_engine.dart' as _i8;
import 'package:ui/features/workflow/services/workflow_persistence.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDirectory_1 extends _i1.SmartFake implements _i2.Directory {
  _FakeDirectory_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_2 extends _i1.SmartFake implements _i2.File {
  _FakeFile_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExecutionResult_3 extends _i1.SmartFake
    implements _i3.ExecutionResult {
  _FakeExecutionResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAsset_4 extends _i1.SmartFake implements _i4.Asset {
  _FakeAsset_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SessionPersistenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionPersistenceService extends _i1.Mock
    implements _i5.SessionPersistenceService {
  MockSessionPersistenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> saveSession(_i7.WorkspaceSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#saveSession, [session]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i7.WorkspaceSession?> loadSession() =>
      (super.noSuchMethod(
            Invocation.method(#loadSession, []),
            returnValue: _i6.Future<_i7.WorkspaceSession?>.value(),
          )
          as _i6.Future<_i7.WorkspaceSession?>);
}

/// A class which mocks [WorkflowEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkflowEngine extends _i1.Mock implements _i8.WorkflowEngine {
  MockWorkflowEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.WorkflowStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i8.WorkflowStatus.idle,
          )
          as _i8.WorkflowStatus);

  @override
  Map<String, dynamic> get variables =>
      (super.noSuchMethod(
            Invocation.getter(#variables),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Duration get elapsedTime =>
      (super.noSuchMethod(
            Invocation.getter(#elapsedTime),
            returnValue: _FakeDuration_0(this, Invocation.getter(#elapsedTime)),
          )
          as Duration);

  @override
  Map<String, int> get nodeExecutionCounts =>
      (super.noSuchMethod(
            Invocation.getter(#nodeExecutionCounts),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<bool> executeAssetNode(_i9.AssetNode? node) =>
      (super.noSuchMethod(
            Invocation.method(#executeAssetNode, [node]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> run(
    _i10.Workflow? workflow, {
    Map<String, String>? assetMap = const {},
    Map<String, String>? assetNameMap = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #run,
              [workflow],
              {#assetMap: assetMap, #assetNameMap: assetNameMap},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void stop() => super.noSuchMethod(
    Invocation.method(#stop, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WorkflowPersistence].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkflowPersistence extends _i1.Mock
    implements _i12.WorkflowPersistence {
  MockWorkflowPersistence() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Directory> get localDirectory =>
      (super.noSuchMethod(
            Invocation.getter(#localDirectory),
            returnValue: _i6.Future<_i2.Directory>.value(
              _FakeDirectory_1(this, Invocation.getter(#localDirectory)),
            ),
          )
          as _i6.Future<_i2.Directory>);

  @override
  _i6.Future<_i2.File> getExportFile() =>
      (super.noSuchMethod(
            Invocation.method(#getExportFile, []),
            returnValue: _i6.Future<_i2.File>.value(
              _FakeFile_2(this, Invocation.method(#getExportFile, [])),
            ),
          )
          as _i6.Future<_i2.File>);

  @override
  _i6.Future<void> saveDraft(_i10.Workflow? workflow) =>
      (super.noSuchMethod(
            Invocation.method(#saveDraft, [workflow]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i10.Workflow?> loadDraft() =>
      (super.noSuchMethod(
            Invocation.method(#loadDraft, []),
            returnValue: _i6.Future<_i10.Workflow?>.value(),
          )
          as _i6.Future<_i10.Workflow?>);

  @override
  _i6.Future<void> exportWorkflow(
    _i10.Workflow? workflow,
    _i2.File? targetFile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#exportWorkflow, [workflow, targetFile]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i10.Workflow?> importWorkflow(_i2.File? sourceFile) =>
      (super.noSuchMethod(
            Invocation.method(#importWorkflow, [sourceFile]),
            returnValue: _i6.Future<_i10.Workflow?>.value(),
          )
          as _i6.Future<_i10.Workflow?>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i13.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i6.Future<Map<String, dynamic>> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i3.ExecutionResult> executeTask(_i15.TaskCommand? task) =>
      (super.noSuchMethod(
            Invocation.method(#executeTask, [task]),
            returnValue: _i6.Future<_i3.ExecutionResult>.value(
              _FakeExecutionResult_3(
                this,
                Invocation.method(#executeTask, [task]),
              ),
            ),
          )
          as _i6.Future<_i3.ExecutionResult>);

  @override
  _i6.Future<_i3.ExecutionResult> checkTask(_i15.TaskCommand? task) =>
      (super.noSuchMethod(
            Invocation.method(#checkTask, [task]),
            returnValue: _i6.Future<_i3.ExecutionResult>.value(
              _FakeExecutionResult_3(
                this,
                Invocation.method(#checkTask, [task]),
              ),
            ),
          )
          as _i6.Future<_i3.ExecutionResult>);

  @override
  _i6.Future<Map<String, dynamic>> abortTask() =>
      (super.noSuchMethod(
            Invocation.method(#abortTask, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> getCursorPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getCursorPosition, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> hideApp() =>
      (super.noSuchMethod(
            Invocation.method(#hideApp, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> showApp() =>
      (super.noSuchMethod(
            Invocation.method(#showApp, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [AssetStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAssetStorageService extends _i1.Mock
    implements _i16.AssetStorageService {
  MockAssetStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i4.Asset>> loadAssets() =>
      (super.noSuchMethod(
            Invocation.method(#loadAssets, []),
            returnValue: _i6.Future<List<_i4.Asset>>.value(<_i4.Asset>[]),
          )
          as _i6.Future<List<_i4.Asset>>);

  @override
  _i6.Future<void> saveAssets(List<_i4.Asset>? assets) =>
      (super.noSuchMethod(
            Invocation.method(#saveAssets, [assets]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.Asset?> importAsset(
    String? sourcePath, {
    String? targetFilename,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importAsset,
              [sourcePath],
              {#targetFilename: targetFilename},
            ),
            returnValue: _i6.Future<_i4.Asset?>.value(),
          )
          as _i6.Future<_i4.Asset?>);

  @override
  _i6.Future<String> generateUniqueFilename(String? originalFilename) =>
      (super.noSuchMethod(
            Invocation.method(#generateUniqueFilename, [originalFilename]),
            returnValue: _i6.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#generateUniqueFilename, [originalFilename]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> getThumbnailPath(_i4.Asset? asset) =>
      (super.noSuchMethod(
            Invocation.method(#getThumbnailPath, [asset]),
            returnValue: _i6.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#getThumbnailPath, [asset]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> deleteAsset(_i4.Asset? asset) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAsset, [asset]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.Asset> renameAsset(_i4.Asset? asset, String? newFilename) =>
      (super.noSuchMethod(
            Invocation.method(#renameAsset, [asset, newFilename]),
            returnValue: _i6.Future<_i4.Asset>.value(
              _FakeAsset_4(
                this,
                Invocation.method(#renameAsset, [asset, newFilename]),
              ),
            ),
          )
          as _i6.Future<_i4.Asset>);

  @override
  _i6.Future<List<_i4.Asset>> scanDirectory() =>
      (super.noSuchMethod(
            Invocation.method(#scanDirectory, []),
            returnValue: _i6.Future<List<_i4.Asset>>.value(<_i4.Asset>[]),
          )
          as _i6.Future<List<_i4.Asset>>);
}
