// Mocks generated by Mockito 5.4.6 from annotations
// in ui/test/features/workflow/workflow_engine_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:ui/core/api_client.dart' as _i3;
import 'package:ui/features/tasks/task_command.dart' as _i6;
import 'package:ui/features/workflow/models/execution_result.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeExecutionResult_0 extends _i1.SmartFake
    implements _i2.ExecutionResult {
  _FakeExecutionResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i3.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i5.Future<Map<String, dynamic>> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i2.ExecutionResult> executeTask(_i6.TaskCommand? task) =>
      (super.noSuchMethod(
            Invocation.method(#executeTask, [task]),
            returnValue: _i5.Future<_i2.ExecutionResult>.value(
              _FakeExecutionResult_0(
                this,
                Invocation.method(#executeTask, [task]),
              ),
            ),
          )
          as _i5.Future<_i2.ExecutionResult>);

  @override
  _i5.Future<Map<String, dynamic>> abortTask() =>
      (super.noSuchMethod(
            Invocation.method(#abortTask, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> getCursorPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getCursorPosition, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);
}
