// Mocks generated by Mockito 5.4.6 from annotations
// in macaque/test/features/assets/asset_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:macaque/features/assets/models/asset.dart' as _i2;
import 'package:macaque/features/assets/services/asset_storage_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAsset_0 extends _i1.SmartFake implements _i2.Asset {
  _FakeAsset_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AssetStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAssetStorageService extends _i1.Mock
    implements _i3.AssetStorageService {
  MockAssetStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Asset>> loadAssets() =>
      (super.noSuchMethod(
            Invocation.method(#loadAssets, []),
            returnValue: _i4.Future<List<_i2.Asset>>.value(<_i2.Asset>[]),
          )
          as _i4.Future<List<_i2.Asset>>);

  @override
  _i4.Future<void> saveAssets(List<_i2.Asset>? assets) =>
      (super.noSuchMethod(
            Invocation.method(#saveAssets, [assets]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Asset?> importAsset(
    String? sourcePath, {
    String? targetFilename,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importAsset,
              [sourcePath],
              {#targetFilename: targetFilename},
            ),
            returnValue: _i4.Future<_i2.Asset?>.value(),
          )
          as _i4.Future<_i2.Asset?>);

  @override
  _i4.Future<String> generateUniqueFilename(String? originalFilename) =>
      (super.noSuchMethod(
            Invocation.method(#generateUniqueFilename, [originalFilename]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#generateUniqueFilename, [originalFilename]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> getThumbnailPath(_i2.Asset? asset) =>
      (super.noSuchMethod(
            Invocation.method(#getThumbnailPath, [asset]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#getThumbnailPath, [asset]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> deleteAsset(_i2.Asset? asset) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAsset, [asset]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Asset> renameAsset(_i2.Asset? asset, String? newFilename) =>
      (super.noSuchMethod(
            Invocation.method(#renameAsset, [asset, newFilename]),
            returnValue: _i4.Future<_i2.Asset>.value(
              _FakeAsset_0(
                this,
                Invocation.method(#renameAsset, [asset, newFilename]),
              ),
            ),
          )
          as _i4.Future<_i2.Asset>);

  @override
  _i4.Future<List<_i2.Asset>> scanDirectory() =>
      (super.noSuchMethod(
            Invocation.method(#scanDirectory, []),
            returnValue: _i4.Future<List<_i2.Asset>>.value(<_i2.Asset>[]),
          )
          as _i4.Future<List<_i2.Asset>>);
}
